from pyfiglet import *
figlet = figlet_format("know your weight in planets of the solar system!",font="digital")
print(figlet)
print("Developed by Ashutosh Wahane")
print()
weight = int(input("Enter your Weight : "))
mass = weight/9.8
print("your mass : ",mass)
print("****************************************")
print("1 : Sun : ",mass*274)
print("2 : Mercury : ",mass*3.7)
print("3 : Venus : ",mass*8.8)
print("4 : Mars : ",mass*3.71)
print("5 : Earth : ",mass*9.8)
print("6 : Jupiter : ",mass*24.92)
print("7 : Saturn : ",mass*10.44)
print("8 : Neptune : ",mass*11.15)
print("9 : Pluto : ",mass*0.58)
print("10 : Moon : ",mass*1.62)